openapi: 3.0.0
info:
  title: Orval example
  version: "1.0"
servers:
  - url: "http://localhost:3000"
paths:
  /example:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: ./ExampleModel.yaml
